In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

im1 = cv2.imread('./image_registration_dataset/rio_register.jpg')          # Image that needs to be registered.
im2 = cv2.imread('./image_registration_dataset/rio_base_1.jpg') # trainImage

im1 = cv2.resize(im1, (600, 600), interpolation= cv2.INTER_LINEAR)
im2 = cv2.resize(im2, (600, 600), interpolation= cv2.INTER_LINEAR)


img1 = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)
img2 = cv2.cvtColor(im2, cv2.COLOR_BGR2GRAY)

# Initiate ORB detector
pts = 50 # your hyper param mostly increase it
orb = cv2.ORB_create(pts)  #Registration works with at least 50 points

# find the keypoints and descriptors with orb
kp1, des1 = orb.detectAndCompute(img1, None)  #kp1 --> list of keypoints
kp2, des2 = orb.detectAndCompute(img2, None)

matcher = cv2.DescriptorMatcher_create(cv2.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)

matches = matcher.match(des1, des2, None)

matches = sorted(matches, key = lambda x:x.distance)

img3 = cv2.drawMatches(im1,kp1, im2, kp2, matches[:10], None)

cv2.imshow("Matches image", img3)
cv2.waitKey(0)

points1 = np.zeros((len(matches), 2), dtype=np.float32)  #Prints empty array of size equal to (matches, 2)
points2 = np.zeros((len(matches), 2), dtype=np.float32)

for i, match in enumerate(matches):
   points1[i, :] = kp1[match.queryIdx].pt    
   points2[i, :] = kp2[match.trainIdx].pt  

h, mask = cv2.findHomography(points1, points2, cv2.RANSAC)
 

height, width, channels = im2.shape
im1Reg = cv2.warpPerspective(im1, h, (width, height))
   
print("Estimated homography : \n",  h)

cv2.imshow("Registered image", im1Reg)
cv2.waitKey()

Estimated homography : 
 [[ 6.98423564e-01 -4.85089541e-02  8.14785696e+01]
 [-2.19601494e-02  1.36061383e+00 -3.92380746e+01]
 [-1.69529488e-06 -2.31555154e-04  1.00000000e+00]]


-1